const CUENTA_SUELDO        = '1'
const CUENTA_AHORRO        = '2'
const CUENTA_PLAZO_FIJO    = '3'
const MAX_CANTIDAD_CUENTA  = 11
const TRANSACCION_RETIRO   = 'S'
const TRANSACCION_DEPOSITO = 'D'
const REGEX_NUM_CUENTA     = /^[0-9]*$/
const TIPO_CUENTAS         = [ '1', '2', '3' ]

module.exports = {
    CUENTA_SUELDO,
    CUENTA_AHORRO,
    CUENTA_PLAZO_FIJO,
    MAX_CANTIDAD_CUENTA,
    TRANSACCION_RETIRO,
    TRANSACCION_DEPOSITO,
    REGEX_NUM_CUENTA,
    TIPO_CUENTAS
}